name: Build and Release Defender Onboarding

on:
  push:
    branches: [ main ]
    paths:
      - 'defender_onboarding/**'  # Only trigger when changes are in this directory :cite[4]
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches: [ main ]
    paths:
      - 'defender_onboarding/**'  # Only run PR checks for changes in this directory

env:
  GO_VERSION: '1.21'  # Specify Go version
  PROJECT_DIR: 'defender_onboarding'  # Define project directory

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}  # Set default working directory :cite[5]:cite[7]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true  # Cache Go modules for faster builds :cite[3]
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build
      run: go build -v -o defender-onboarding .

  release:
    if: startsWith(github.ref, 'refs/tags/')  # Only run on tag pushes :cite[1]
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Build for multiple platforms
      run: |
        cd ${{ env.PROJECT_DIR }}
        platforms=(
          "linux/amd64"
          "linux/arm64"
          "darwin/amd64"
          "darwin/arm64"
          "windows/amd64"
        )
        
        for platform in "${platforms[@]}"; do
          GOOS=${platform%/*} GOARCH=${platform#*/} go build -o defender-onboarding-$GOOS-$GOARCH
        done
        mv defender-onboarding-windows-amd64 defender-onboarding-windows-amd64.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          defender_onboarding/defender-onboarding-*
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for Defender Onboarding
          - Built from tag ${{ github.ref_name }}
          - Includes binaries for multiple platforms
